# Generated by Django 4.0.3 on 2022-04-19 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_Creacion_Tbl_Stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('total', models.FloatField()),
                ('nro_doc_cliente', models.CharField(max_length=12)),
                ('tipo_doc_cliente', models.CharField(choices=[['RUC', 'RUC'], ['DNI', 'DNI']], max_length=5)),
                ('mesa', models.IntegerField()),
                ('propina', models.FloatField()),
                ('usuarioId', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('pedidoId', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedidos', to='fact_electr.pedido')),
                ('stockId', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedidos', to='menu.stock')),
            ],
            options={
                'db_table': 'tbl_detalle_pedidos',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('serie', models.CharField(max_length=5)),
                ('numero', models.CharField(max_length=10)),
                ('pdf', models.TextField()),
                ('cdr', models.TextField()),
                ('xml', models.TextField()),
                ('tipo', models.CharField(choices=[['BOLETA', 'BOLETA'], ['FACTURA', 'FACTURA']], max_length=10)),
                ('pedido', models.OneToOneField(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='fact_electr.pedido')),
            ],
            options={
                'db_table': 'tbl_comprobantes',
                'unique_together': {('serie', 'numero')},
            },
        ),
    ]
