# Generated by Django 4.0.3 on 2022-04-20 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fact_electr', '0001_Creacion_Tbl_pedido_comprobante_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 2, 41, 52, 122056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nro_doc_cliente',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_doc_cliente',
            field=models.CharField(choices=[['RUC', 'RUC'], ['DNI', 'DNI']], max_length=5, null=True),
        ),
    ]
