# Generated by Django 4.0.3 on 2022-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_Creacion_tabla_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('categoria', models.CharField(choices=[('TODO', 'TO_DO'), ('IP', 'IN_PROGRESS'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='TODO', max_length=45)),
                ('fechaCaducidad', models.DateTimeField(db_column='fecha_caducidad')),
                ('importancia', models.IntegerField()),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='create_at')),
                ('updateAt', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('etiquetas', models.ManyToManyField(related_name='tareas', to='app.etiqueta')),
            ],
            options={
                'db_table': 'tbl_tareas',
            },
        ),
    ]
