# Generated by Django 4.0.3 on 2022-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_Add_Columna_Descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default='---', null=True),
        ),
    ]
